### PR TITLE
Add NEON support for 4x4 DCT.

### PR DESCRIPTION
**Pull request by andreasgal**

### CODE REVIEW

**Comment by tdaede** [comment]
this is landed but disabled by default due to bugs.

**Comment by andreasgal** [comment]
What are the bugs?

**Comment by tdaede** [comment]
It fails in dcttest due to some overflows I haven't tracked down yet.

https://review.xiph.org/932/

**Comment by andreasgal** [comment]
This used to work. Not sure that changed. I won't have time to debug this. Sorry :(

**Comment by tdaede** [comment]
That's OK, I didn't expect you to. I will enable it once we figure out what went wrong.

**Pull request closed without merging**
