### PR TITLE
Remove dependency on libogg for daala core

### PR DESCRIPTION
**Pull request by iankronquist**
I'm sure that this isn't right because I don't quite understand how the repository is laid out. I'm not sure which files go into libdaala(base|dec|enc) so I started by replacing everything under `/src/`.
Here is the test output from my mac:
```
============================================================================
Testsuite summary for daala 0.0-1021-g8a85647
============================================================================
# TOTAL: 7
# PASS:  6
# SKIP:  1
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

### CODE REVIEW

**Comment by iankronquist** [comment]
@tdaede I addressed your suggestions. I also rebased off of master and squashed everything into one commit. Is there anything more you would like to see?

**Comment by iankronquist** [comment]
@tdaede Addressed style nitpicks

**Comment by iankronquist** [comment]
@tdaede rebased again because of changes on master.

**Comment by tdaede** [comment]
Merged, thanks!

**Pull request closed without merging**
